name: Build and Publish
on:
  push:
    tags:
      - 'msf-release-[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_LITE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BAHMNI_LITE_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.BAHMNI_LITE_AWS_REGION }}

      - name: Download OMODs
        run: aws s3 cp s3://stable/$GITHUB_REF_NAME/ target/ --recursive

      - name: Build docker image
        run: docker build -t openmrs-amman:latest -f package/docker/openmrs/Dockerfile .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'openmrs-amman:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          trivyignores: ./.trivyignore
          vuln-type: 'os,library'
          severity: 'CRITICAL'
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image tag varaible
        run: echo "ARTIFACT_VERSION=$(cat package/.appversion)-$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Tag and Push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: bahmni-msf-lite/openmrs-amman
          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
        run: |
          echo $APP_VERSION
          docker tag openmrs-amman:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
