name: Build and Publish OpenMRS
on:
  push:
    branches:
      - githubActions
  workflow_dispatch:

jobs:
  build-publish-docker-helm:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_LITE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BAHMNI_LITE_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.BAHMNI_LITE_AWS_REGION }}

      - name: Download OMODs
        env:
          BUCKET_NAME: v2-artefacts
        run: |
          aws s3 cp s3://$BUCKET_NAME/openmrs-module-appointments/latest/ target/ --recursive
          aws s3 cp s3://$BUCKET_NAME/openmrs-module-bahmni.ie.apps/latest/ target/ --recursive
          aws s3 cp s3://$BUCKET_NAME/patient-identifier-generator/latest/ target/ --recursive
          aws s3 cp s3://$BUCKET_NAME/bahmni-core/latest/ target/ --recursive
          aws s3 cp s3://$BUCKET_NAME/visit-close-module/latest/ target/ --recursive
      
      - name: show
        run: ls -al target